Pm 116 route for account deletion
CharlesRigal/projet-moto-back pull request #41
Opened 2024-03-19 14:46 UTC by CharlesRigal

ajout de la route pour supprimer un compte utilisateur

2024-03-19 14:51 UTC, RichardDuclos requested changes
pour verifier si l'utilisateur est admin il y a la dependence admin_depency au lieu de faire user_dependency puis verifier user.role == admin
et il faut une route pour faire une demande de suppression a base d'email + mot de passe, qui ajoute une ligne dans une table "user_delete_request" si l'email et mdp correspondent

2024-03-19 14:52 UTC, RichardDuclos commented
ou carrement suppression du compte directement si on veut pas se faire chier mais il faut email + mot de passe pour verifier que c'est bien le bon utilisateur

2024-04-18 16:11 UTC, CharlesRigal commented
c'est ré-ouvert avec les modifs que tu voulais

2024-04-18 17:06 UTC, RichardDuclos approved these changes

2024-04-18 17:06 UTC, merged